[package]
name = "recless"
version = "0.1.0"
authors = ["Richard Janis Goldschmidt <janis.beckert@gmail.com>"]
repository = "https://github.com/SuperFluffy/rust-recless"

[lib]
name = "recless"

[dependencies]
ndarray = "0.9"

[features]
blas = ["ndarray/blas"]
